// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package protocs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	WorkAt               string   `protobuf:"bytes,4,opt,name=WorkAt,proto3" json:"WorkAt,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	IsActive             bool     `protobuf:"varint,7,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Profile) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Profile) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Profile) GetWorkAt() string {
	if m != nil {
		return m.WorkAt
	}
	return ""
}

func (m *Profile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Profile) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type UserGetProfileArguments struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	WorkAt               string   `protobuf:"bytes,4,opt,name=WorkAt,proto3" json:"WorkAt,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetProfileArguments) Reset()         { *m = UserGetProfileArguments{} }
func (m *UserGetProfileArguments) String() string { return proto.CompactTextString(m) }
func (*UserGetProfileArguments) ProtoMessage()    {}
func (*UserGetProfileArguments) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *UserGetProfileArguments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetProfileArguments.Unmarshal(m, b)
}
func (m *UserGetProfileArguments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetProfileArguments.Marshal(b, m, deterministic)
}
func (m *UserGetProfileArguments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetProfileArguments.Merge(m, src)
}
func (m *UserGetProfileArguments) XXX_Size() int {
	return xxx_messageInfo_UserGetProfileArguments.Size(m)
}
func (m *UserGetProfileArguments) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetProfileArguments.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetProfileArguments proto.InternalMessageInfo

func (m *UserGetProfileArguments) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserGetProfileArguments) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserGetProfileArguments) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserGetProfileArguments) GetWorkAt() string {
	if m != nil {
		return m.WorkAt
	}
	return ""
}

func (m *UserGetProfileArguments) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserGetProfileArguments) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func init() {
	proto.RegisterType((*Profile)(nil), "protocs.Profile")
	proto.RegisterType((*UserGetProfileArguments)(nil), "protocs.UserGetProfileArguments")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x91, 0x41, 0x4a, 0xc4, 0x30,
	0x14, 0x86, 0x4d, 0x47, 0xa7, 0xf5, 0xc9, 0x88, 0x64, 0xa1, 0xa1, 0x6e, 0x4a, 0x57, 0x5d, 0x75,
	0x40, 0x4f, 0x10, 0xa9, 0x0c, 0xdd, 0xc8, 0x50, 0x18, 0x5c, 0xdb, 0xc9, 0x9b, 0x3a, 0xd8, 0x36,
	0x25, 0x49, 0x05, 0x6f, 0xe3, 0x05, 0x3c, 0x80, 0xb7, 0x93, 0xa6, 0x71, 0x74, 0xe3, 0xaa, 0x1b,
	0x57, 0xe1, 0x7b, 0xef, 0xfd, 0x3f, 0xff, 0x4f, 0x60, 0xd1, 0x29, 0xb9, 0xdb, 0xd7, 0x98, 0x76,
	0x4a, 0x1a, 0x49, 0x7d, 0xfb, 0x6c, 0x75, 0x78, 0x5d, 0x49, 0x59, 0xd5, 0xb8, 0xb4, 0x5c, 0xf6,
	0xbb, 0x25, 0x36, 0x9d, 0x79, 0x1b, 0xaf, 0xe2, 0x4f, 0x02, 0xfe, 0x7a, 0xd4, 0xd1, 0x73, 0xf0,
	0xf2, 0x8c, 0x91, 0x88, 0x24, 0xb3, 0xc2, 0xcb, 0x33, 0x7a, 0x09, 0xf3, 0x8d, 0x46, 0x95, 0x67,
	0xcc, 0xb3, 0x33, 0x47, 0x94, 0x81, 0xcf, 0x85, 0x50, 0xa8, 0x35, 0x9b, 0x45, 0x24, 0x39, 0x2d,
	0xbe, 0x71, 0x50, 0x3c, 0x4a, 0xf5, 0xc2, 0x0d, 0x3b, 0xb6, 0x0b, 0x47, 0x34, 0x82, 0xb3, 0xf5,
	0xb3, 0x6c, 0xf1, 0xa1, 0x6f, 0x4a, 0x54, 0xec, 0xc4, 0x2e, 0x7f, 0x8f, 0x06, 0xe5, 0x0a, 0x5b,
	0x81, 0x8a, 0xcd, 0x47, 0xe5, 0x48, 0x34, 0x84, 0x20, 0xd7, 0x7c, 0x6b, 0xf6, 0xaf, 0xc8, 0xfc,
	0x88, 0x24, 0x41, 0x71, 0xe0, 0xf8, 0x83, 0xc0, 0xd5, 0x10, 0x69, 0x85, 0xc6, 0x55, 0xe0, 0xaa,
	0xea, 0x1b, 0x6c, 0x8d, 0xfe, 0x8f, 0x5d, 0x6e, 0xde, 0x3d, 0x08, 0x5c, 0x50, 0x4d, 0xef, 0x00,
	0x7e, 0x72, 0xd3, 0x28, 0x75, 0xbf, 0x95, 0xfe, 0x51, 0x28, 0xbc, 0x38, 0x5c, 0xb8, 0x55, 0x7c,
	0x34, 0x78, 0x70, 0x21, 0xa6, 0x79, 0xdc, 0xc3, 0x62, 0xd3, 0x89, 0x27, 0x83, 0x93, 0x6d, 0x32,
	0xac, 0x71, 0xa2, 0x4d, 0x39, 0xb7, 0xa3, 0xdb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x40,
	0xf6, 0x16, 0xcc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfilesClient is the client API for Profiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfilesClient interface {
	GetProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error)
	AddProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error)
	UpdateProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error)
	DeleteProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error)
}

type profilesClient struct {
	cc *grpc.ClientConn
}

func NewProfilesClient(cc *grpc.ClientConn) ProfilesClient {
	return &profilesClient{cc}
}

func (c *profilesClient) GetProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protocs.Profiles/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) AddProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protocs.Profiles/AddProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) UpdateProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protocs.Profiles/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesClient) DeleteProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protocs.Profiles/DeleteProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilesServer is the server API for Profiles service.
type ProfilesServer interface {
	GetProfile(context.Context, *UserGetProfileArguments) (*Profile, error)
	AddProfile(context.Context, *UserGetProfileArguments) (*Profile, error)
	UpdateProfile(context.Context, *UserGetProfileArguments) (*Profile, error)
	DeleteProfile(context.Context, *UserGetProfileArguments) (*Profile, error)
}

// UnimplementedProfilesServer can be embedded to have forward compatible implementations.
type UnimplementedProfilesServer struct {
}

func (*UnimplementedProfilesServer) GetProfile(ctx context.Context, req *UserGetProfileArguments) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (*UnimplementedProfilesServer) AddProfile(ctx context.Context, req *UserGetProfileArguments) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProfile not implemented")
}
func (*UnimplementedProfilesServer) UpdateProfile(ctx context.Context, req *UserGetProfileArguments) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (*UnimplementedProfilesServer) DeleteProfile(ctx context.Context, req *UserGetProfileArguments) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}

func RegisterProfilesServer(s *grpc.Server, srv ProfilesServer) {
	s.RegisterService(&_Profiles_serviceDesc, srv)
}

func _Profiles_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProfileArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocs.Profiles/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).GetProfile(ctx, req.(*UserGetProfileArguments))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_AddProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProfileArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).AddProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocs.Profiles/AddProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).AddProfile(ctx, req.(*UserGetProfileArguments))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProfileArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocs.Profiles/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).UpdateProfile(ctx, req.(*UserGetProfileArguments))
	}
	return interceptor(ctx, in, info, handler)
}

func _Profiles_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProfileArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocs.Profiles/DeleteProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).DeleteProfile(ctx, req.(*UserGetProfileArguments))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profiles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocs.Profiles",
	HandlerType: (*ProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _Profiles_GetProfile_Handler,
		},
		{
			MethodName: "AddProfile",
			Handler:    _Profiles_AddProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _Profiles_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _Profiles_DeleteProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
