// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package protocs

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	WorkAt               string   `protobuf:"bytes,4,opt,name=WorkAt,proto3" json:"WorkAt,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	IsActive             bool     `protobuf:"varint,7,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Profile) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Profile) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Profile) GetWorkAt() string {
	if m != nil {
		return m.WorkAt
	}
	return ""
}

func (m *Profile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Profile) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

type UserGetProfileArguments struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	WorkAt               string   `protobuf:"bytes,4,opt,name=WorkAt,proto3" json:"WorkAt,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetProfileArguments) Reset()         { *m = UserGetProfileArguments{} }
func (m *UserGetProfileArguments) String() string { return proto.CompactTextString(m) }
func (*UserGetProfileArguments) ProtoMessage()    {}
func (*UserGetProfileArguments) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *UserGetProfileArguments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetProfileArguments.Unmarshal(m, b)
}
func (m *UserGetProfileArguments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetProfileArguments.Marshal(b, m, deterministic)
}
func (m *UserGetProfileArguments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetProfileArguments.Merge(m, src)
}
func (m *UserGetProfileArguments) XXX_Size() int {
	return xxx_messageInfo_UserGetProfileArguments.Size(m)
}
func (m *UserGetProfileArguments) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetProfileArguments.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetProfileArguments proto.InternalMessageInfo

func (m *UserGetProfileArguments) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserGetProfileArguments) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserGetProfileArguments) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserGetProfileArguments) GetWorkAt() string {
	if m != nil {
		return m.WorkAt
	}
	return ""
}

func (m *UserGetProfileArguments) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserGetProfileArguments) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func init() {
	proto.RegisterType((*Profile)(nil), "protocs.Profile")
	proto.RegisterType((*UserGetProfileArguments)(nil), "protocs.UserGetProfileArguments")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x91, 0xc1, 0x4e, 0xb3, 0x40,
	0x14, 0x85, 0xff, 0xa1, 0x7f, 0xa1, 0x5e, 0x53, 0x63, 0x66, 0xa1, 0x13, 0xdc, 0x10, 0x56, 0xac,
	0x68, 0xa2, 0x4f, 0x80, 0xc1, 0x34, 0x6c, 0x4c, 0x43, 0xd2, 0xb8, 0x96, 0xce, 0x2d, 0x36, 0x02,
	0x43, 0x66, 0x06, 0x13, 0x1f, 0xc6, 0x47, 0xf0, 0x01, 0x7c, 0x3b, 0x33, 0xc3, 0x58, 0xdd, 0xb8,
	0x62, 0xe3, 0x8a, 0x7c, 0xf7, 0xdc, 0x73, 0xb8, 0x27, 0x03, 0xcb, 0x5e, 0x8a, 0xfd, 0xa1, 0xc1,
	0xb4, 0x97, 0x42, 0x0b, 0x1a, 0xd8, 0xcf, 0x4e, 0x85, 0x57, 0xb5, 0x10, 0x75, 0x83, 0x2b, 0xcb,
	0xd5, 0xb0, 0x5f, 0x61, 0xdb, 0xeb, 0xd7, 0x71, 0x2b, 0xfe, 0x20, 0x10, 0x6c, 0x46, 0x1f, 0x3d,
	0x03, 0xaf, 0xc8, 0x19, 0x89, 0x48, 0x32, 0x2b, 0xbd, 0x22, 0xa7, 0x17, 0xe0, 0x6f, 0x15, 0xca,
	0x22, 0x67, 0x9e, 0x9d, 0x39, 0xa2, 0x0c, 0x82, 0x8c, 0x73, 0x89, 0x4a, 0xb1, 0x59, 0x44, 0x92,
	0x93, 0xf2, 0x0b, 0x8d, 0xe3, 0x41, 0xc8, 0xe7, 0x4c, 0xb3, 0xff, 0x56, 0x70, 0x44, 0x23, 0x38,
	0xdd, 0x3c, 0x89, 0x0e, 0xef, 0x87, 0xb6, 0x42, 0xc9, 0xe6, 0x56, 0xfc, 0x39, 0x32, 0xce, 0x35,
	0x76, 0x1c, 0x25, 0xf3, 0x47, 0xe7, 0x48, 0x34, 0x84, 0x45, 0xa1, 0xb2, 0x9d, 0x3e, 0xbc, 0x20,
	0x0b, 0x22, 0x92, 0x2c, 0xca, 0x23, 0xc7, 0xef, 0x04, 0x2e, 0xcd, 0x49, 0x6b, 0xd4, 0xae, 0x42,
	0x26, 0xeb, 0xa1, 0xc5, 0x4e, 0xab, 0xbf, 0xd8, 0xe5, 0xfa, 0xcd, 0x83, 0xb9, 0xf9, 0xad, 0xa2,
	0xb7, 0x00, 0xdf, 0x47, 0xd3, 0x28, 0x75, 0x4f, 0x95, 0xfe, 0xd2, 0x26, 0x3c, 0x3f, 0x6e, 0x38,
	0x29, 0xfe, 0x67, 0x32, 0x32, 0xce, 0xa7, 0x65, 0xdc, 0xc1, 0x72, 0xdb, 0xf3, 0x47, 0x8d, 0x93,
	0x63, 0x72, 0x6c, 0x70, 0x62, 0x4c, 0xe5, 0xdb, 0xd1, 0xcd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x9c, 0xa0, 0x72, 0x65, 0xc9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	GetProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error)
	AddProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error)
	UpdateProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error)
	DeleteProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) GetProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protocs.Users/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) AddProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protocs.Users/AddProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) UpdateProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protocs.Users/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) DeleteProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protocs.Users/DeleteProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	GetProfile(context.Context, *UserGetProfileArguments) (*Profile, error)
	AddProfile(context.Context, *UserGetProfileArguments) (*Profile, error)
	UpdateProfile(context.Context, *UserGetProfileArguments) (*Profile, error)
	DeleteProfile(context.Context, *UserGetProfileArguments) (*Profile, error)
}

// UnimplementedUsersServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServer struct {
}

func (*UnimplementedUsersServer) GetProfile(ctx context.Context, req *UserGetProfileArguments) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (*UnimplementedUsersServer) AddProfile(ctx context.Context, req *UserGetProfileArguments) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProfile not implemented")
}
func (*UnimplementedUsersServer) UpdateProfile(ctx context.Context, req *UserGetProfileArguments) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (*UnimplementedUsersServer) DeleteProfile(ctx context.Context, req *UserGetProfileArguments) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProfileArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocs.Users/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).GetProfile(ctx, req.(*UserGetProfileArguments))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_AddProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProfileArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).AddProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocs.Users/AddProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).AddProfile(ctx, req.(*UserGetProfileArguments))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProfileArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocs.Users/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).UpdateProfile(ctx, req.(*UserGetProfileArguments))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProfileArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocs.Users/DeleteProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).DeleteProfile(ctx, req.(*UserGetProfileArguments))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocs.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _Users_GetProfile_Handler,
		},
		{
			MethodName: "AddProfile",
			Handler:    _Users_AddProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _Users_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _Users_DeleteProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
