// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package models

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	WorkAt               string   `protobuf:"bytes,4,opt,name=WorkAt,proto3" json:"WorkAt,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	IsActive             bool     `protobuf:"varint,7,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Profile) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Profile) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Profile) GetWorkAt() string {
	if m != nil {
		return m.WorkAt
	}
	return ""
}

func (m *Profile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Profile) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Profile) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Profile) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type UserGetProfileArguments struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	WorkAt               string   `protobuf:"bytes,4,opt,name=WorkAt,proto3" json:"WorkAt,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=PhoneNumber,proto3" json:"PhoneNumber,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetProfileArguments) Reset()         { *m = UserGetProfileArguments{} }
func (m *UserGetProfileArguments) String() string { return proto.CompactTextString(m) }
func (*UserGetProfileArguments) ProtoMessage()    {}
func (*UserGetProfileArguments) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *UserGetProfileArguments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetProfileArguments.Unmarshal(m, b)
}
func (m *UserGetProfileArguments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetProfileArguments.Marshal(b, m, deterministic)
}
func (m *UserGetProfileArguments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetProfileArguments.Merge(m, src)
}
func (m *UserGetProfileArguments) XXX_Size() int {
	return xxx_messageInfo_UserGetProfileArguments.Size(m)
}
func (m *UserGetProfileArguments) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetProfileArguments.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetProfileArguments proto.InternalMessageInfo

func (m *UserGetProfileArguments) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserGetProfileArguments) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserGetProfileArguments) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserGetProfileArguments) GetWorkAt() string {
	if m != nil {
		return m.WorkAt
	}
	return ""
}

func (m *UserGetProfileArguments) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserGetProfileArguments) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func init() {
	proto.RegisterType((*Profile)(nil), "protocs.Profile")
	proto.RegisterType((*UserGetProfileArguments)(nil), "protocs.UserGetProfileArguments")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x71, 0x0a, 0xf9, 0x73, 0x08, 0x84, 0x3c, 0x80, 0x55, 0x31, 0x58, 0x99, 0x32, 0x65,
	0x80, 0x27, 0x30, 0x44, 0xaa, 0xb2, 0x54, 0x55, 0xa4, 0x8a, 0x99, 0xd6, 0x07, 0x54, 0xd0, 0x38,
	0x3a, 0xbb, 0xbc, 0x15, 0x8f, 0xc7, 0x8e, 0xe2, 0x98, 0x84, 0x85, 0xbd, 0x93, 0xf5, 0xfd, 0x7e,
	0xfe, 0xa4, 0x3b, 0x1b, 0x2e, 0x3a, 0x32, 0x2f, 0xbb, 0x0f, 0x2c, 0x3b, 0x32, 0xce, 0xf0, 0xc4,
	0x1f, 0x5b, 0x9b, 0x7f, 0x33, 0x48, 0x56, 0x83, 0xe2, 0x97, 0x10, 0xd5, 0x95, 0x60, 0x92, 0x15,
	0xb3, 0x26, 0xaa, 0x2b, 0x7e, 0x0d, 0xf1, 0xda, 0x22, 0xd5, 0x95, 0x88, 0x3c, 0x0b, 0x89, 0x0b,
	0x48, 0x94, 0xd6, 0x84, 0xd6, 0x8a, 0x99, 0x64, 0x45, 0xd6, 0xfc, 0xc6, 0xbe, 0xf1, 0x64, 0xe8,
	0x5d, 0x39, 0x71, 0xea, 0x45, 0x48, 0x5c, 0xc2, 0xf9, 0xea, 0xcd, 0xb4, 0xb8, 0x3c, 0xec, 0x37,
	0x48, 0xe2, 0xcc, 0xcb, 0xbf, 0xa8, 0x6f, 0x2e, 0xb0, 0xd5, 0x48, 0x22, 0x1e, 0x9a, 0x43, 0xe2,
	0x73, 0x48, 0x6b, 0xab, 0xb6, 0x6e, 0xf7, 0x89, 0x22, 0x91, 0xac, 0x48, 0x9b, 0x31, 0xf3, 0x5b,
	0xc8, 0x1e, 0x09, 0x9f, 0x1d, 0x6a, 0xe5, 0x44, 0xea, 0x6b, 0x13, 0xe8, 0xed, 0xba, 0xd3, 0xc1,
	0x66, 0x83, 0x1d, 0x41, 0xfe, 0xc5, 0xe0, 0xa6, 0x5f, 0x67, 0x81, 0x2e, 0xac, 0xaf, 0xe8, 0xf5,
	0xb0, 0xc7, 0xd6, 0xd9, 0x63, 0x7c, 0x87, 0xbb, 0x25, 0xa4, 0x61, 0x4e, 0xcb, 0x1f, 0x00, 0xa6,
	0xb1, 0xb9, 0x2c, 0xc3, 0x5f, 0x96, 0xff, 0xec, 0x33, 0xbf, 0x1a, 0x6f, 0x04, 0x95, 0x9f, 0x6c,
	0x62, 0x8f, 0xee, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xa2, 0x0a, 0x58, 0x18, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfilesClient is the client API for Profiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfilesClient interface {
	GetProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error)
}

type profilesClient struct {
	cc *grpc.ClientConn
}

func NewProfilesClient(cc *grpc.ClientConn) ProfilesClient {
	return &profilesClient{cc}
}

func (c *profilesClient) GetProfile(ctx context.Context, in *UserGetProfileArguments, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/protocs.Profiles/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilesServer is the server API for Profiles service.
type ProfilesServer interface {
	GetProfile(context.Context, *UserGetProfileArguments) (*Profile, error)
}

// UnimplementedProfilesServer can be embedded to have forward compatible implementations.
type UnimplementedProfilesServer struct {
}

func (*UnimplementedProfilesServer) GetProfile(ctx context.Context, req *UserGetProfileArguments) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}

func RegisterProfilesServer(s *grpc.Server, srv ProfilesServer) {
	s.RegisterService(&_Profiles_serviceDesc, srv)
}

func _Profiles_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetProfileArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocs.Profiles/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesServer).GetProfile(ctx, req.(*UserGetProfileArguments))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profiles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocs.Profiles",
	HandlerType: (*ProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _Profiles_GetProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile.proto",
}
